services:
  leaf_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaf_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always