services:
  veggie_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veggie_app
    ports:
      - "5000:5000"  
    volumes:
      - .:/app       
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
