services:
  veggie_toon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veggie_toon
    ports:
      - "5000:5000"
    volumes:
      - .:/app  
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
